version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: browser-notificator-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=price-alerts-browser
    restart: unless-stopped