version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-db-demo
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=price-alerts-subs
    restart: unless-stopped